# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """AgentService 定义 GoFrame 后端可远程调用的 Python Agent gRPC 服务。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HealthCheck = channel.unary_unary(
                '/agent.AgentService/HealthCheck',
                request_serializer=agent__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=agent__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.ProcessArticles = channel.unary_unary(
                '/agent.AgentService/ProcessArticles',
                request_serializer=agent__pb2.ProcessArticlesRequest.SerializeToString,
                response_deserializer=agent__pb2.ProcessArticlesResponse.FromString,
                _registered_method=True)
        self.ProcessFeedback = channel.unary_unary(
                '/agent.AgentService/ProcessFeedback',
                request_serializer=agent__pb2.ProcessFeedbackRequest.SerializeToString,
                response_deserializer=agent__pb2.ProcessFeedbackResponse.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """AgentService 定义 GoFrame 后端可远程调用的 Python Agent gRPC 服务。
    """

    def HealthCheck(self, request, context):
        """HealthCheck 用于检查 Python Agent Service 是否在线。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessArticles(self, request, context):
        """ProcessArticles 触发文章筛选、摘要、改写和校验流程。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessFeedback(self, request, context):
        """ProcessFeedback 触发反馈提取和用户画像更新流程。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=agent__pb2.HealthCheckRequest.FromString,
                    response_serializer=agent__pb2.HealthCheckResponse.SerializeToString,
            ),
            'ProcessArticles': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessArticles,
                    request_deserializer=agent__pb2.ProcessArticlesRequest.FromString,
                    response_serializer=agent__pb2.ProcessArticlesResponse.SerializeToString,
            ),
            'ProcessFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessFeedback,
                    request_deserializer=agent__pb2.ProcessFeedbackRequest.FromString,
                    response_serializer=agent__pb2.ProcessFeedbackResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agent.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agent.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """AgentService 定义 GoFrame 后端可远程调用的 Python Agent gRPC 服务。
    """

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/HealthCheck',
            agent__pb2.HealthCheckRequest.SerializeToString,
            agent__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessArticles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ProcessArticles',
            agent__pb2.ProcessArticlesRequest.SerializeToString,
            agent__pb2.ProcessArticlesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agent.AgentService/ProcessFeedback',
            agent__pb2.ProcessFeedbackRequest.SerializeToString,
            agent__pb2.ProcessFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
