// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Article struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	RawText       string                 `protobuf:"bytes,4,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	Source        string                 `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	PublishedAt   string                 `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	Tags          []string               `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *Article) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Article) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Article) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type McpPolicy struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MockTransport   bool                   `protobuf:"varint,1,opt,name=mock_transport,json=mockTransport,proto3" json:"mock_transport,omitempty"`
	EnableEmbedding bool                   `protobuf:"varint,2,opt,name=enable_embedding,json=enableEmbedding,proto3" json:"enable_embedding,omitempty"`
	EnableFetch     bool                   `protobuf:"varint,3,opt,name=enable_fetch,json=enableFetch,proto3" json:"enable_fetch,omitempty"`
	EnableMilvus    bool                   `protobuf:"varint,4,opt,name=enable_milvus,json=enableMilvus,proto3" json:"enable_milvus,omitempty"`
	EnableNeo4J     bool                   `protobuf:"varint,5,opt,name=enable_neo4j,json=enableNeo4j,proto3" json:"enable_neo4j,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *McpPolicy) Reset() {
	*x = McpPolicy{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpPolicy) ProtoMessage() {}

func (x *McpPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpPolicy.ProtoReflect.Descriptor instead.
func (*McpPolicy) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *McpPolicy) GetMockTransport() bool {
	if x != nil {
		return x.MockTransport
	}
	return false
}

func (x *McpPolicy) GetEnableEmbedding() bool {
	if x != nil {
		return x.EnableEmbedding
	}
	return false
}

func (x *McpPolicy) GetEnableFetch() bool {
	if x != nil {
		return x.EnableFetch
	}
	return false
}

func (x *McpPolicy) GetEnableMilvus() bool {
	if x != nil {
		return x.EnableMilvus
	}
	return false
}

func (x *McpPolicy) GetEnableNeo4J() bool {
	if x != nil {
		return x.EnableNeo4J
	}
	return false
}

type McpCallLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerName    string                 `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	ToolName      string                 `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	RequestJson   string                 `protobuf:"bytes,3,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	ResponseJson  string                 `protobuf:"bytes,4,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	Success       bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	LatencyMs     int64                  `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	RunId         string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	AgentName     string                 `protobuf:"bytes,8,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpCallLog) Reset() {
	*x = McpCallLog{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpCallLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpCallLog) ProtoMessage() {}

func (x *McpCallLog) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpCallLog.ProtoReflect.Descriptor instead.
func (*McpCallLog) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *McpCallLog) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *McpCallLog) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *McpCallLog) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

func (x *McpCallLog) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

func (x *McpCallLog) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *McpCallLog) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *McpCallLog) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *McpCallLog) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *McpCallLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *McpCallLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ProcessArticlesRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunId               string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Articles            []*Article             `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	UserProfileSnapshot map[string]string      `protobuf:"bytes,3,rep,name=user_profile_snapshot,json=userProfileSnapshot,proto3" json:"user_profile_snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	McpPolicy           *McpPolicy             `protobuf:"bytes,4,opt,name=mcp_policy,json=mcpPolicy,proto3" json:"mcp_policy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessArticlesRequest) Reset() {
	*x = ProcessArticlesRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticlesRequest) ProtoMessage() {}

func (x *ProcessArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticlesRequest.ProtoReflect.Descriptor instead.
func (*ProcessArticlesRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessArticlesRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessArticlesRequest) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ProcessArticlesRequest) GetUserProfileSnapshot() map[string]string {
	if x != nil {
		return x.UserProfileSnapshot
	}
	return nil
}

func (x *ProcessArticlesRequest) GetMcpPolicy() *McpPolicy {
	if x != nil {
		return x.McpPolicy
	}
	return nil
}

type ArticleProcessResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArticleId     string                 `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	Keep          bool                   `protobuf:"varint,2,opt,name=keep,proto3" json:"keep,omitempty"`
	Score         float64                `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	Summary       string                 `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	PostText      string                 `protobuf:"bytes,5,opt,name=post_text,json=postText,proto3" json:"post_text,omitempty"`
	CheckPass     bool                   `protobuf:"varint,6,opt,name=check_pass,json=checkPass,proto3" json:"check_pass,omitempty"`
	Issues        []string               `protobuf:"bytes,7,rep,name=issues,proto3" json:"issues,omitempty"`
	McpCallLogs   []*McpCallLog          `protobuf:"bytes,8,rep,name=mcp_call_logs,json=mcpCallLogs,proto3" json:"mcp_call_logs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArticleProcessResult) Reset() {
	*x = ArticleProcessResult{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleProcessResult) ProtoMessage() {}

func (x *ArticleProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleProcessResult.ProtoReflect.Descriptor instead.
func (*ArticleProcessResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ArticleProcessResult) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleProcessResult) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

func (x *ArticleProcessResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ArticleProcessResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleProcessResult) GetPostText() string {
	if x != nil {
		return x.PostText
	}
	return ""
}

func (x *ArticleProcessResult) GetCheckPass() bool {
	if x != nil {
		return x.CheckPass
	}
	return false
}

func (x *ArticleProcessResult) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ArticleProcessResult) GetMcpCallLogs() []*McpCallLog {
	if x != nil {
		return x.McpCallLogs
	}
	return nil
}

type ProcessArticlesResponse struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	RunId         string                  `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Results       []*ArticleProcessResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessArticlesResponse) Reset() {
	*x = ProcessArticlesResponse{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticlesResponse) ProtoMessage() {}

func (x *ProcessArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticlesResponse.ProtoReflect.Descriptor instead.
func (*ProcessArticlesResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ProcessArticlesResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessArticlesResponse) GetResults() []*ArticleProcessResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type FeedbackItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FeedbackId    string                 `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ArticleId     string                 `protobuf:"bytes,3,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	PostId        string                 `protobuf:"bytes,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	FeedbackText  string                 `protobuf:"bytes,5,opt,name=feedback_text,json=feedbackText,proto3" json:"feedback_text,omitempty"`
	FeedbackType  string                 `protobuf:"bytes,6,opt,name=feedback_type,json=feedbackType,proto3" json:"feedback_type,omitempty"`
	Rating        int32                  `protobuf:"varint,7,opt,name=rating,proto3" json:"rating,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackItem) Reset() {
	*x = FeedbackItem{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackItem) ProtoMessage() {}

func (x *FeedbackItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackItem.ProtoReflect.Descriptor instead.
func (*FeedbackItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *FeedbackItem) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *FeedbackItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedbackItem) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *FeedbackItem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *FeedbackItem) GetFeedbackText() string {
	if x != nil {
		return x.FeedbackText
	}
	return ""
}

func (x *FeedbackItem) GetFeedbackType() string {
	if x != nil {
		return x.FeedbackType
	}
	return ""
}

func (x *FeedbackItem) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *FeedbackItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type ProcessFeedbackRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	RunId               string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Feedback            []*FeedbackItem        `protobuf:"bytes,2,rep,name=feedback,proto3" json:"feedback,omitempty"`
	UserProfileSnapshot map[string]string      `protobuf:"bytes,3,rep,name=user_profile_snapshot,json=userProfileSnapshot,proto3" json:"user_profile_snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	McpPolicy           *McpPolicy             `protobuf:"bytes,4,opt,name=mcp_policy,json=mcpPolicy,proto3" json:"mcp_policy,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *ProcessFeedbackRequest) Reset() {
	*x = ProcessFeedbackRequest{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFeedbackRequest) ProtoMessage() {}

func (x *ProcessFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFeedbackRequest.ProtoReflect.Descriptor instead.
func (*ProcessFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ProcessFeedbackRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessFeedbackRequest) GetFeedback() []*FeedbackItem {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ProcessFeedbackRequest) GetUserProfileSnapshot() map[string]string {
	if x != nil {
		return x.UserProfileSnapshot
	}
	return nil
}

func (x *ProcessFeedbackRequest) GetMcpPolicy() *McpPolicy {
	if x != nil {
		return x.McpPolicy
	}
	return nil
}

type ProcessFeedbackResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	RunId                  string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Sentiment              string                 `protobuf:"bytes,2,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	ExtractedFeedback      []string               `protobuf:"bytes,3,rep,name=extracted_feedback,json=extractedFeedback,proto3" json:"extracted_feedback,omitempty"`
	UpdatedProfileSnapshot map[string]string      `protobuf:"bytes,4,rep,name=updated_profile_snapshot,json=updatedProfileSnapshot,proto3" json:"updated_profile_snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	McpCallLogs            []*McpCallLog          `protobuf:"bytes,5,rep,name=mcp_call_logs,json=mcpCallLogs,proto3" json:"mcp_call_logs,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ProcessFeedbackResponse) Reset() {
	*x = ProcessFeedbackResponse{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFeedbackResponse) ProtoMessage() {}

func (x *ProcessFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFeedbackResponse.ProtoReflect.Descriptor instead.
func (*ProcessFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessFeedbackResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessFeedbackResponse) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *ProcessFeedbackResponse) GetExtractedFeedback() []string {
	if x != nil {
		return x.ExtractedFeedback
	}
	return nil
}

func (x *ProcessFeedbackResponse) GetUpdatedProfileSnapshot() map[string]string {
	if x != nil {
		return x.UpdatedProfileSnapshot
	}
	return nil
}

func (x *ProcessFeedbackResponse) GetMcpCallLogs() []*McpCallLog {
	if x != nil {
		return x.McpCallLogs
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Client        string                 `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	EnabledAgents []string               `protobuf:"bytes,3,rep,name=enabled_agents,json=enabledAgents,proto3" json:"enabled_agents,omitempty"`
	MockMode      bool                   `protobuf:"varint,4,opt,name=mock_mode,json=mockMode,proto3" json:"mock_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetEnabledAgents() []string {
	if x != nil {
		return x.EnabledAgents
	}
	return nil
}

func (x *HealthCheckResponse) GetMockMode() bool {
	if x != nil {
		return x.MockMode
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xba\x01\n" +
	"\aArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x19\n" +
	"\braw_text\x18\x04 \x01(\tR\arawText\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xc8\x01\n" +
	"\tMcpPolicy\x12%\n" +
	"\x0emock_transport\x18\x01 \x01(\bR\rmockTransport\x12)\n" +
	"\x10enable_embedding\x18\x02 \x01(\bR\x0fenableEmbedding\x12!\n" +
	"\fenable_fetch\x18\x03 \x01(\bR\venableFetch\x12#\n" +
	"\renable_milvus\x18\x04 \x01(\bR\fenableMilvus\x12!\n" +
	"\fenable_neo4j\x18\x05 \x01(\bR\venableNeo4j\"\xbe\x02\n" +
	"\n" +
	"McpCallLog\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12!\n" +
	"\frequest_json\x18\x03 \x01(\tR\vrequestJson\x12#\n" +
	"\rresponse_json\x18\x04 \x01(\tR\fresponseJson\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\b \x01(\tR\tagentName\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\"\xc0\x02\n" +
	"\x16ProcessArticlesRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12*\n" +
	"\barticles\x18\x02 \x03(\v2\x0e.agent.ArticleR\barticles\x12j\n" +
	"\x15user_profile_snapshot\x18\x03 \x03(\v26.agent.ProcessArticlesRequest.UserProfileSnapshotEntryR\x13userProfileSnapshot\x12/\n" +
	"\n" +
	"mcp_policy\x18\x04 \x01(\v2\x10.agent.McpPolicyR\tmcpPolicy\x1aF\n" +
	"\x18UserProfileSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x84\x02\n" +
	"\x14ArticleProcessResult\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x12\n" +
	"\x04keep\x18\x02 \x01(\bR\x04keep\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1b\n" +
	"\tpost_text\x18\x05 \x01(\tR\bpostText\x12\x1d\n" +
	"\n" +
	"check_pass\x18\x06 \x01(\bR\tcheckPass\x12\x16\n" +
	"\x06issues\x18\a \x03(\tR\x06issues\x125\n" +
	"\rmcp_call_logs\x18\b \x03(\v2\x11.agent.McpCallLogR\vmcpCallLogs\"g\n" +
	"\x17ProcessArticlesResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x125\n" +
	"\aresults\x18\x02 \x03(\v2\x1b.agent.ArticleProcessResultR\aresults\"\xde\x02\n" +
	"\fFeedbackItem\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x03 \x01(\tR\tarticleId\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\tR\x06postId\x12#\n" +
	"\rfeedback_text\x18\x05 \x01(\tR\ffeedbackText\x12#\n" +
	"\rfeedback_type\x18\x06 \x01(\tR\ffeedbackType\x12\x16\n" +
	"\x06rating\x18\a \x01(\x05R\x06rating\x12=\n" +
	"\bmetadata\x18\b \x03(\v2!.agent.FeedbackItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x16ProcessFeedbackRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12/\n" +
	"\bfeedback\x18\x02 \x03(\v2\x13.agent.FeedbackItemR\bfeedback\x12j\n" +
	"\x15user_profile_snapshot\x18\x03 \x03(\v26.agent.ProcessFeedbackRequest.UserProfileSnapshotEntryR\x13userProfileSnapshot\x12/\n" +
	"\n" +
	"mcp_policy\x18\x04 \x01(\v2\x10.agent.McpPolicyR\tmcpPolicy\x1aF\n" +
	"\x18UserProfileSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf5\x02\n" +
	"\x17ProcessFeedbackResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1c\n" +
	"\tsentiment\x18\x02 \x01(\tR\tsentiment\x12-\n" +
	"\x12extracted_feedback\x18\x03 \x03(\tR\x11extractedFeedback\x12t\n" +
	"\x18updated_profile_snapshot\x18\x04 \x03(\v2:.agent.ProcessFeedbackResponse.UpdatedProfileSnapshotEntryR\x16updatedProfileSnapshot\x125\n" +
	"\rmcp_call_logs\x18\x05 \x03(\v2\x11.agent.McpCallLogR\vmcpCallLogs\x1aI\n" +
	"\x1bUpdatedProfileSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x12HealthCheckRequest\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\"\x8b\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eenabled_agents\x18\x03 \x03(\tR\renabledAgents\x12\x1b\n" +
	"\tmock_mode\x18\x04 \x01(\bR\bmockMode2\xf8\x01\n" +
	"\fAgentService\x12D\n" +
	"\vHealthCheck\x12\x19.agent.HealthCheckRequest\x1a\x1a.agent.HealthCheckResponse\x12P\n" +
	"\x0fProcessArticles\x12\x1d.agent.ProcessArticlesRequest\x1a\x1e.agent.ProcessArticlesResponse\x12P\n" +
	"\x0fProcessFeedback\x12\x1d.agent.ProcessFeedbackRequest\x1a\x1e.agent.ProcessFeedbackResponseB$Z\"knowledge-post-agent/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_agent_proto_goTypes = []any{
	(*Article)(nil),                 // 0: agent.Article
	(*McpPolicy)(nil),               // 1: agent.McpPolicy
	(*McpCallLog)(nil),              // 2: agent.McpCallLog
	(*ProcessArticlesRequest)(nil),  // 3: agent.ProcessArticlesRequest
	(*ArticleProcessResult)(nil),    // 4: agent.ArticleProcessResult
	(*ProcessArticlesResponse)(nil), // 5: agent.ProcessArticlesResponse
	(*FeedbackItem)(nil),            // 6: agent.FeedbackItem
	(*ProcessFeedbackRequest)(nil),  // 7: agent.ProcessFeedbackRequest
	(*ProcessFeedbackResponse)(nil), // 8: agent.ProcessFeedbackResponse
	(*HealthCheckRequest)(nil),      // 9: agent.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 10: agent.HealthCheckResponse
	nil,                             // 11: agent.ProcessArticlesRequest.UserProfileSnapshotEntry
	nil,                             // 12: agent.FeedbackItem.MetadataEntry
	nil,                             // 13: agent.ProcessFeedbackRequest.UserProfileSnapshotEntry
	nil,                             // 14: agent.ProcessFeedbackResponse.UpdatedProfileSnapshotEntry
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: agent.ProcessArticlesRequest.articles:type_name -> agent.Article
	11, // 1: agent.ProcessArticlesRequest.user_profile_snapshot:type_name -> agent.ProcessArticlesRequest.UserProfileSnapshotEntry
	1,  // 2: agent.ProcessArticlesRequest.mcp_policy:type_name -> agent.McpPolicy
	2,  // 3: agent.ArticleProcessResult.mcp_call_logs:type_name -> agent.McpCallLog
	4,  // 4: agent.ProcessArticlesResponse.results:type_name -> agent.ArticleProcessResult
	12, // 5: agent.FeedbackItem.metadata:type_name -> agent.FeedbackItem.MetadataEntry
	6,  // 6: agent.ProcessFeedbackRequest.feedback:type_name -> agent.FeedbackItem
	13, // 7: agent.ProcessFeedbackRequest.user_profile_snapshot:type_name -> agent.ProcessFeedbackRequest.UserProfileSnapshotEntry
	1,  // 8: agent.ProcessFeedbackRequest.mcp_policy:type_name -> agent.McpPolicy
	14, // 9: agent.ProcessFeedbackResponse.updated_profile_snapshot:type_name -> agent.ProcessFeedbackResponse.UpdatedProfileSnapshotEntry
	2,  // 10: agent.ProcessFeedbackResponse.mcp_call_logs:type_name -> agent.McpCallLog
	9,  // 11: agent.AgentService.HealthCheck:input_type -> agent.HealthCheckRequest
	3,  // 12: agent.AgentService.ProcessArticles:input_type -> agent.ProcessArticlesRequest
	7,  // 13: agent.AgentService.ProcessFeedback:input_type -> agent.ProcessFeedbackRequest
	10, // 14: agent.AgentService.HealthCheck:output_type -> agent.HealthCheckResponse
	5,  // 15: agent.AgentService.ProcessArticles:output_type -> agent.ProcessArticlesResponse
	8,  // 16: agent.AgentService.ProcessFeedback:output_type -> agent.ProcessFeedbackResponse
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
