// 文件作用：
// 本文件定义 GoFrame 后端与 Python Agent Service 之间的 gRPC 通信协议。
// GoFrame 根据该协议构造请求，Python Agent 根据该协议返回文章处理、反馈处理和健康检查结果。
//
// 主要内容：
// 1. Article：GoFrame 抓取或读取到的文章输入结构。
// 2. McpPolicy：一次请求中 MCP 工具能力开关。
// 3. McpCallLog：Python Agent 调用 MCP Tool 后返回的日志结构。
// 4. ProcessArticles：文章筛选、摘要、改写、校验接口。
// 5. ProcessFeedback：用户反馈提取和 user_profile_snapshot 更新接口。
// 6. HealthCheck：Python Agent Service 健康检查接口。
//
// 阅读建议：
// 先理解 message 表示跨语言传输的数据结构，再理解 service 中的 rpc 表示可被远程调用的方法。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: agent.proto

// package 决定 protobuf 类型在协议层的命名空间。

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Article 表示一篇待处理文章。
// GoFrame 后端抓取 RSS 或读取数据库后，会把文章字段填入这里并发送给 Python Agent。
type Article struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// article_id 是文章唯一标识，用于把 Python 返回结果对应回 articles/posts 表。
	ArticleId string `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// url 是原文链接，CheckAgent 会用它判断输出是否可追溯。
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// title 是文章标题，FilterAgent 会把它作为筛选重要信号。
	Title string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	// raw_text 是文章正文，SummaryAgent 会用它生成摘要。
	RawText string `protobuf:"bytes,4,opt,name=raw_text,json=rawText,proto3" json:"raw_text,omitempty"`
	// source 表示文章来源，例如 RSS 源名称。
	Source string `protobuf:"bytes,5,opt,name=source,proto3" json:"source,omitempty"`
	// published_at 保存发布时间字符串，Python Agent 当前不解析时间格式。
	PublishedAt string `protobuf:"bytes,6,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	// tags 是文章标签列表，repeated 表示可以有多个字符串值。
	Tags          []string `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Article) Reset() {
	*x = Article{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Article) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Article) ProtoMessage() {}

func (x *Article) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Article.ProtoReflect.Descriptor instead.
func (*Article) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *Article) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *Article) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Article) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Article) GetRawText() string {
	if x != nil {
		return x.RawText
	}
	return ""
}

func (x *Article) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Article) GetPublishedAt() string {
	if x != nil {
		return x.PublishedAt
	}
	return ""
}

func (x *Article) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// McpPolicy 表示本次请求允许 Python Agent 使用哪些 MCP 能力。
// Python Agent 会把它转换成 dict，并和默认策略合并。
type McpPolicy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// mock_transport 表示是否使用 mock MCP 传输层；真实选择还会结合 Python 配置 settings.mock_mcp。
	MockTransport bool `protobuf:"varint,1,opt,name=mock_transport,json=mockTransport,proto3" json:"mock_transport,omitempty"`
	// enable_embedding 控制是否允许调用 embedding-mcp。
	EnableEmbedding bool `protobuf:"varint,2,opt,name=enable_embedding,json=enableEmbedding,proto3" json:"enable_embedding,omitempty"`
	// enable_fetch 控制是否允许调用 fetch-mcp 拉取网页正文。
	EnableFetch bool `protobuf:"varint,3,opt,name=enable_fetch,json=enableFetch,proto3" json:"enable_fetch,omitempty"`
	// enable_milvus 控制是否允许调用 milvus-mcp 做向量检索。
	EnableMilvus bool `protobuf:"varint,4,opt,name=enable_milvus,json=enableMilvus,proto3" json:"enable_milvus,omitempty"`
	// enable_neo4j 控制是否允许调用 neo4j-mcp 读取或更新用户兴趣图谱。
	EnableNeo4J   bool `protobuf:"varint,5,opt,name=enable_neo4j,json=enableNeo4j,proto3" json:"enable_neo4j,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpPolicy) Reset() {
	*x = McpPolicy{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpPolicy) ProtoMessage() {}

func (x *McpPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpPolicy.ProtoReflect.Descriptor instead.
func (*McpPolicy) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *McpPolicy) GetMockTransport() bool {
	if x != nil {
		return x.MockTransport
	}
	return false
}

func (x *McpPolicy) GetEnableEmbedding() bool {
	if x != nil {
		return x.EnableEmbedding
	}
	return false
}

func (x *McpPolicy) GetEnableFetch() bool {
	if x != nil {
		return x.EnableFetch
	}
	return false
}

func (x *McpPolicy) GetEnableMilvus() bool {
	if x != nil {
		return x.EnableMilvus
	}
	return false
}

func (x *McpPolicy) GetEnableNeo4J() bool {
	if x != nil {
		return x.EnableNeo4J
	}
	return false
}

// McpCallLog 表示一次 MCP Tool 调用日志。
// Python Agent 在 BaseMcpClient 中生成该日志，GoFrame 后端可写入 mcp_call_logs 表。
type McpCallLog struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// server_name 是 MCP Server 名称，例如 embedding-mcp、neo4j-mcp。
	ServerName string `protobuf:"bytes,1,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	// tool_name 是被调用的 MCP Tool 名称，例如 embed_text。
	ToolName string `protobuf:"bytes,2,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	// request_json 保存 JSON-RPC 请求体文本，便于后续排查入参。
	RequestJson string `protobuf:"bytes,3,opt,name=request_json,json=requestJson,proto3" json:"request_json,omitempty"`
	// response_json 保存 JSON-RPC 响应体文本，便于排查工具输出。
	ResponseJson string `protobuf:"bytes,4,opt,name=response_json,json=responseJson,proto3" json:"response_json,omitempty"`
	// success 表示调用是否成功完成。
	Success bool `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	// latency_ms 表示调用耗时，单位毫秒。
	LatencyMs int64 `protobuf:"varint,6,opt,name=latency_ms,json=latencyMs,proto3" json:"latency_ms,omitempty"`
	// run_id 用于关联一次完整任务。
	RunId string `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// agent_name 表示哪个 Agent 发起该 MCP 调用。
	AgentName string `protobuf:"bytes,8,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	// status 保存 success、failed、denied 等更细状态。
	Status string `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	// error_message 保存失败或权限拒绝原因。
	ErrorMessage  string `protobuf:"bytes,10,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CallId        string `protobuf:"bytes,11,opt,name=call_id,json=callId,proto3" json:"call_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *McpCallLog) Reset() {
	*x = McpCallLog{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *McpCallLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*McpCallLog) ProtoMessage() {}

func (x *McpCallLog) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use McpCallLog.ProtoReflect.Descriptor instead.
func (*McpCallLog) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *McpCallLog) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

func (x *McpCallLog) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *McpCallLog) GetRequestJson() string {
	if x != nil {
		return x.RequestJson
	}
	return ""
}

func (x *McpCallLog) GetResponseJson() string {
	if x != nil {
		return x.ResponseJson
	}
	return ""
}

func (x *McpCallLog) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *McpCallLog) GetLatencyMs() int64 {
	if x != nil {
		return x.LatencyMs
	}
	return 0
}

func (x *McpCallLog) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *McpCallLog) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *McpCallLog) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *McpCallLog) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *McpCallLog) GetCallId() string {
	if x != nil {
		return x.CallId
	}
	return ""
}

// ProcessArticlesRequest 是文章处理 RPC 的请求。
// GoFrame 发送文章列表、用户画像快照和 MCP 策略，Python Agent 返回处理结果。
type ProcessArticlesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id 是本次任务 id，缺失时 Python Agent 会自动生成。
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// articles 是待处理文章列表。
	Articles []*Article `protobuf:"bytes,2,rep,name=articles,proto3" json:"articles,omitempty"`
	// user_profile_snapshot 是用户画像快照；map<string,string> 便于 Go/Python 跨语言传输。
	UserProfileSnapshot map[string]string `protobuf:"bytes,3,rep,name=user_profile_snapshot,json=userProfileSnapshot,proto3" json:"user_profile_snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mcp_policy 是本次请求的 MCP 能力开关。
	McpPolicy     *McpPolicy `protobuf:"bytes,4,opt,name=mcp_policy,json=mcpPolicy,proto3" json:"mcp_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessArticlesRequest) Reset() {
	*x = ProcessArticlesRequest{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticlesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticlesRequest) ProtoMessage() {}

func (x *ProcessArticlesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticlesRequest.ProtoReflect.Descriptor instead.
func (*ProcessArticlesRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessArticlesRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessArticlesRequest) GetArticles() []*Article {
	if x != nil {
		return x.Articles
	}
	return nil
}

func (x *ProcessArticlesRequest) GetUserProfileSnapshot() map[string]string {
	if x != nil {
		return x.UserProfileSnapshot
	}
	return nil
}

func (x *ProcessArticlesRequest) GetMcpPolicy() *McpPolicy {
	if x != nil {
		return x.McpPolicy
	}
	return nil
}

type ScoreBreakdownItem struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Dimension       string                 `protobuf:"bytes,1,opt,name=dimension,proto3" json:"dimension,omitempty"`
	Available       bool                   `protobuf:"varint,2,opt,name=available,proto3" json:"available,omitempty"`
	RawScore        float64                `protobuf:"fixed64,3,opt,name=raw_score,json=rawScore,proto3" json:"raw_score,omitempty"`
	NormalizedScore float64                `protobuf:"fixed64,4,opt,name=normalized_score,json=normalizedScore,proto3" json:"normalized_score,omitempty"`
	Weight          float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Contribution    float64                `protobuf:"fixed64,6,opt,name=contribution,proto3" json:"contribution,omitempty"`
	Evidence        []string               `protobuf:"bytes,7,rep,name=evidence,proto3" json:"evidence,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ScoreBreakdownItem) Reset() {
	*x = ScoreBreakdownItem{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScoreBreakdownItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScoreBreakdownItem) ProtoMessage() {}

func (x *ScoreBreakdownItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScoreBreakdownItem.ProtoReflect.Descriptor instead.
func (*ScoreBreakdownItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ScoreBreakdownItem) GetDimension() string {
	if x != nil {
		return x.Dimension
	}
	return ""
}

func (x *ScoreBreakdownItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *ScoreBreakdownItem) GetRawScore() float64 {
	if x != nil {
		return x.RawScore
	}
	return 0
}

func (x *ScoreBreakdownItem) GetNormalizedScore() float64 {
	if x != nil {
		return x.NormalizedScore
	}
	return 0
}

func (x *ScoreBreakdownItem) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *ScoreBreakdownItem) GetContribution() float64 {
	if x != nil {
		return x.Contribution
	}
	return 0
}

func (x *ScoreBreakdownItem) GetEvidence() []string {
	if x != nil {
		return x.Evidence
	}
	return nil
}

// ArticleProcessResult 是单篇文章的处理结果。
// Python Agent 会把 Filter/Summary/Rewrite/Check 的结果汇总到这里。
type ArticleProcessResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// article_id 对应输入文章 id。
	ArticleId string `protobuf:"bytes,1,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// keep 表示文章是否通过筛选并进入摘要改写流程。
	Keep bool `protobuf:"varint,2,opt,name=keep,proto3" json:"keep,omitempty"`
	// score 是 FilterAgent 给出的相关性分数。
	Score float64 `protobuf:"fixed64,3,opt,name=score,proto3" json:"score,omitempty"`
	// summary 是 SummaryAgent 生成的中文摘要。
	Summary string `protobuf:"bytes,4,opt,name=summary,proto3" json:"summary,omitempty"`
	// post_text 是 RewriteAgent 生成的推文或知识笔记正文。
	PostText string `protobuf:"bytes,5,opt,name=post_text,json=postText,proto3" json:"post_text,omitempty"`
	// check_pass 表示 CheckAgent 校验是否通过。
	CheckPass bool `protobuf:"varint,6,opt,name=check_pass,json=checkPass,proto3" json:"check_pass,omitempty"`
	// issues 累积过滤、LLM fallback、校验等阶段发现的问题。
	Issues []string `protobuf:"bytes,7,rep,name=issues,proto3" json:"issues,omitempty"`
	// mcp_call_logs 是该文章处理过程中产生的 MCP 调用日志。
	McpCallLogs           []*McpCallLog         `protobuf:"bytes,8,rep,name=mcp_call_logs,json=mcpCallLogs,proto3" json:"mcp_call_logs,omitempty"`
	ScoreBreakdown        []*ScoreBreakdownItem `protobuf:"bytes,9,rep,name=score_breakdown,json=scoreBreakdown,proto3" json:"score_breakdown,omitempty"`
	RecommendationReasons []string              `protobuf:"bytes,10,rep,name=recommendation_reasons,json=recommendationReasons,proto3" json:"recommendation_reasons,omitempty"`
	RejectionReasons      []string              `protobuf:"bytes,11,rep,name=rejection_reasons,json=rejectionReasons,proto3" json:"rejection_reasons,omitempty"`
	RankPosition          int32                 `protobuf:"varint,12,opt,name=rank_position,json=rankPosition,proto3" json:"rank_position,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ArticleProcessResult) Reset() {
	*x = ArticleProcessResult{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArticleProcessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArticleProcessResult) ProtoMessage() {}

func (x *ArticleProcessResult) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArticleProcessResult.ProtoReflect.Descriptor instead.
func (*ArticleProcessResult) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ArticleProcessResult) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *ArticleProcessResult) GetKeep() bool {
	if x != nil {
		return x.Keep
	}
	return false
}

func (x *ArticleProcessResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *ArticleProcessResult) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *ArticleProcessResult) GetPostText() string {
	if x != nil {
		return x.PostText
	}
	return ""
}

func (x *ArticleProcessResult) GetCheckPass() bool {
	if x != nil {
		return x.CheckPass
	}
	return false
}

func (x *ArticleProcessResult) GetIssues() []string {
	if x != nil {
		return x.Issues
	}
	return nil
}

func (x *ArticleProcessResult) GetMcpCallLogs() []*McpCallLog {
	if x != nil {
		return x.McpCallLogs
	}
	return nil
}

func (x *ArticleProcessResult) GetScoreBreakdown() []*ScoreBreakdownItem {
	if x != nil {
		return x.ScoreBreakdown
	}
	return nil
}

func (x *ArticleProcessResult) GetRecommendationReasons() []string {
	if x != nil {
		return x.RecommendationReasons
	}
	return nil
}

func (x *ArticleProcessResult) GetRejectionReasons() []string {
	if x != nil {
		return x.RejectionReasons
	}
	return nil
}

func (x *ArticleProcessResult) GetRankPosition() int32 {
	if x != nil {
		return x.RankPosition
	}
	return 0
}

// ProcessArticlesResponse 是文章处理 RPC 的响应。
type ProcessArticlesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id 回传本次任务 id，便于 GoFrame 关联运行日志。
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// results 是每篇文章对应的处理结果列表。
	Results       []*ArticleProcessResult `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessArticlesResponse) Reset() {
	*x = ProcessArticlesResponse{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessArticlesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessArticlesResponse) ProtoMessage() {}

func (x *ProcessArticlesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessArticlesResponse.ProtoReflect.Descriptor instead.
func (*ProcessArticlesResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ProcessArticlesResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessArticlesResponse) GetResults() []*ArticleProcessResult {
	if x != nil {
		return x.Results
	}
	return nil
}

// FeedbackItem 表示一条用户反馈。
// GoFrame 可从 feedback_logs 或接口请求中组装这些字段。
type FeedbackItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// feedback_id 是反馈记录 id。
	FeedbackId string `protobuf:"bytes,1,opt,name=feedback_id,json=feedbackId,proto3" json:"feedback_id,omitempty"`
	// user_id 是反馈所属用户。
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// article_id 是反馈关联的文章 id。
	ArticleId string `protobuf:"bytes,3,opt,name=article_id,json=articleId,proto3" json:"article_id,omitempty"`
	// post_id 是反馈关联的生成结果 id。
	PostId string `protobuf:"bytes,4,opt,name=post_id,json=postId,proto3" json:"post_id,omitempty"`
	// feedback_text 是用户输入的自然语言反馈。
	FeedbackText string `protobuf:"bytes,5,opt,name=feedback_text,json=feedbackText,proto3" json:"feedback_text,omitempty"`
	// feedback_type 表示点赞、收藏、不喜欢等反馈类别。
	FeedbackType string `protobuf:"bytes,6,opt,name=feedback_type,json=feedbackType,proto3" json:"feedback_type,omitempty"`
	// rating 是评分，Python mock LLM 会用它辅助判断正负向情绪。
	Rating int32 `protobuf:"varint,7,opt,name=rating,proto3" json:"rating,omitempty"`
	// metadata 保存额外键值信息。
	Metadata      map[string]string `protobuf:"bytes,8,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeedbackItem) Reset() {
	*x = FeedbackItem{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeedbackItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedbackItem) ProtoMessage() {}

func (x *FeedbackItem) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedbackItem.ProtoReflect.Descriptor instead.
func (*FeedbackItem) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *FeedbackItem) GetFeedbackId() string {
	if x != nil {
		return x.FeedbackId
	}
	return ""
}

func (x *FeedbackItem) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *FeedbackItem) GetArticleId() string {
	if x != nil {
		return x.ArticleId
	}
	return ""
}

func (x *FeedbackItem) GetPostId() string {
	if x != nil {
		return x.PostId
	}
	return ""
}

func (x *FeedbackItem) GetFeedbackText() string {
	if x != nil {
		return x.FeedbackText
	}
	return ""
}

func (x *FeedbackItem) GetFeedbackType() string {
	if x != nil {
		return x.FeedbackType
	}
	return ""
}

func (x *FeedbackItem) GetRating() int32 {
	if x != nil {
		return x.Rating
	}
	return 0
}

func (x *FeedbackItem) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// ProcessFeedbackRequest 是用户反馈处理 RPC 的请求。
type ProcessFeedbackRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id 是本次反馈处理任务 id。
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// feedback 是待处理反馈列表。
	Feedback []*FeedbackItem `protobuf:"bytes,2,rep,name=feedback,proto3" json:"feedback,omitempty"`
	// user_profile_snapshot 是当前用户画像快照，Python Agent 会在副本上更新。
	UserProfileSnapshot map[string]string `protobuf:"bytes,3,rep,name=user_profile_snapshot,json=userProfileSnapshot,proto3" json:"user_profile_snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mcp_policy 控制 MemoryAgent 是否可以调用 embedding/neo4j 等工具。
	McpPolicy     *McpPolicy `protobuf:"bytes,4,opt,name=mcp_policy,json=mcpPolicy,proto3" json:"mcp_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessFeedbackRequest) Reset() {
	*x = ProcessFeedbackRequest{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFeedbackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFeedbackRequest) ProtoMessage() {}

func (x *ProcessFeedbackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFeedbackRequest.ProtoReflect.Descriptor instead.
func (*ProcessFeedbackRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ProcessFeedbackRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessFeedbackRequest) GetFeedback() []*FeedbackItem {
	if x != nil {
		return x.Feedback
	}
	return nil
}

func (x *ProcessFeedbackRequest) GetUserProfileSnapshot() map[string]string {
	if x != nil {
		return x.UserProfileSnapshot
	}
	return nil
}

func (x *ProcessFeedbackRequest) GetMcpPolicy() *McpPolicy {
	if x != nil {
		return x.McpPolicy
	}
	return nil
}

// ProcessFeedbackResponse 是用户反馈处理 RPC 的响应。
type ProcessFeedbackResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// run_id 回传本次任务 id。
	RunId string `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	// sentiment 是 FeedbackAgent 判断出的整体情绪。
	Sentiment string `protobuf:"bytes,2,opt,name=sentiment,proto3" json:"sentiment,omitempty"`
	// extracted_feedback 是从用户反馈中提取出的偏好信号。
	ExtractedFeedback []string `protobuf:"bytes,3,rep,name=extracted_feedback,json=extractedFeedback,proto3" json:"extracted_feedback,omitempty"`
	// updated_profile_snapshot 是 MemoryAgent 更新后的用户画像快照，GoFrame 可写入 user_profile_snapshot 表。
	UpdatedProfileSnapshot map[string]string `protobuf:"bytes,4,rep,name=updated_profile_snapshot,json=updatedProfileSnapshot,proto3" json:"updated_profile_snapshot,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// mcp_call_logs 是反馈处理过程中产生的 MCP 调用日志。
	McpCallLogs []*McpCallLog `protobuf:"bytes,5,rep,name=mcp_call_logs,json=mcpCallLogs,proto3" json:"mcp_call_logs,omitempty"`
	// structured_feedback_json 保存 FeedbackAgent 抽取出的结构化反馈 JSON。
	StructuredFeedbackJson string `protobuf:"bytes,6,opt,name=structured_feedback_json,json=structuredFeedbackJson,proto3" json:"structured_feedback_json,omitempty"`
	// profile_diff_json 保存 MemoryAgent 生成的画像变化差异 JSON。
	ProfileDiffJson string `protobuf:"bytes,7,opt,name=profile_diff_json,json=profileDiffJson,proto3" json:"profile_diff_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ProcessFeedbackResponse) Reset() {
	*x = ProcessFeedbackResponse{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessFeedbackResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessFeedbackResponse) ProtoMessage() {}

func (x *ProcessFeedbackResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessFeedbackResponse.ProtoReflect.Descriptor instead.
func (*ProcessFeedbackResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ProcessFeedbackResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *ProcessFeedbackResponse) GetSentiment() string {
	if x != nil {
		return x.Sentiment
	}
	return ""
}

func (x *ProcessFeedbackResponse) GetExtractedFeedback() []string {
	if x != nil {
		return x.ExtractedFeedback
	}
	return nil
}

func (x *ProcessFeedbackResponse) GetUpdatedProfileSnapshot() map[string]string {
	if x != nil {
		return x.UpdatedProfileSnapshot
	}
	return nil
}

func (x *ProcessFeedbackResponse) GetMcpCallLogs() []*McpCallLog {
	if x != nil {
		return x.McpCallLogs
	}
	return nil
}

func (x *ProcessFeedbackResponse) GetStructuredFeedbackJson() string {
	if x != nil {
		return x.StructuredFeedbackJson
	}
	return ""
}

func (x *ProcessFeedbackResponse) GetProfileDiffJson() string {
	if x != nil {
		return x.ProfileDiffJson
	}
	return ""
}

// HealthCheckRequest 是健康检查请求。
type HealthCheckRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// client 可用于标记调用方名称，当前 Python Agent 不强依赖该字段。
	Client        string `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *HealthCheckRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

// HealthCheckResponse 是健康检查响应。
type HealthCheckResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status 表示服务状态，例如 SERVING。
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// version 表示 Python Agent Service 版本。
	Version string `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// enabled_agents 返回当前工作流中启用的 Agent 名称。
	EnabledAgents []string `protobuf:"bytes,3,rep,name=enabled_agents,json=enabledAgents,proto3" json:"enabled_agents,omitempty"`
	// mock_mode 表示当前是否包含 mock LLM 或 mock MCP。
	MockMode      bool `protobuf:"varint,4,opt,name=mock_mode,json=mockMode,proto3" json:"mock_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthCheckResponse) GetEnabledAgents() []string {
	if x != nil {
		return x.EnabledAgents
	}
	return nil
}

func (x *HealthCheckResponse) GetMockMode() bool {
	if x != nil {
		return x.MockMode
	}
	return false
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x05agent\"\xba\x01\n" +
	"\aArticle\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x19\n" +
	"\braw_text\x18\x04 \x01(\tR\arawText\x12\x16\n" +
	"\x06source\x18\x05 \x01(\tR\x06source\x12!\n" +
	"\fpublished_at\x18\x06 \x01(\tR\vpublishedAt\x12\x12\n" +
	"\x04tags\x18\a \x03(\tR\x04tags\"\xc8\x01\n" +
	"\tMcpPolicy\x12%\n" +
	"\x0emock_transport\x18\x01 \x01(\bR\rmockTransport\x12)\n" +
	"\x10enable_embedding\x18\x02 \x01(\bR\x0fenableEmbedding\x12!\n" +
	"\fenable_fetch\x18\x03 \x01(\bR\venableFetch\x12#\n" +
	"\renable_milvus\x18\x04 \x01(\bR\fenableMilvus\x12!\n" +
	"\fenable_neo4j\x18\x05 \x01(\bR\venableNeo4j\"\xd7\x02\n" +
	"\n" +
	"McpCallLog\x12\x1f\n" +
	"\vserver_name\x18\x01 \x01(\tR\n" +
	"serverName\x12\x1b\n" +
	"\ttool_name\x18\x02 \x01(\tR\btoolName\x12!\n" +
	"\frequest_json\x18\x03 \x01(\tR\vrequestJson\x12#\n" +
	"\rresponse_json\x18\x04 \x01(\tR\fresponseJson\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x1d\n" +
	"\n" +
	"latency_ms\x18\x06 \x01(\x03R\tlatencyMs\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"agent_name\x18\b \x01(\tR\tagentName\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\n" +
	" \x01(\tR\ferrorMessage\x12\x17\n" +
	"\acall_id\x18\v \x01(\tR\x06callId\"\xc0\x02\n" +
	"\x16ProcessArticlesRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12*\n" +
	"\barticles\x18\x02 \x03(\v2\x0e.agent.ArticleR\barticles\x12j\n" +
	"\x15user_profile_snapshot\x18\x03 \x03(\v26.agent.ProcessArticlesRequest.UserProfileSnapshotEntryR\x13userProfileSnapshot\x12/\n" +
	"\n" +
	"mcp_policy\x18\x04 \x01(\v2\x10.agent.McpPolicyR\tmcpPolicy\x1aF\n" +
	"\x18UserProfileSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xf0\x01\n" +
	"\x12ScoreBreakdownItem\x12\x1c\n" +
	"\tdimension\x18\x01 \x01(\tR\tdimension\x12\x1c\n" +
	"\tavailable\x18\x02 \x01(\bR\tavailable\x12\x1b\n" +
	"\traw_score\x18\x03 \x01(\x01R\brawScore\x12)\n" +
	"\x10normalized_score\x18\x04 \x01(\x01R\x0fnormalizedScore\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12\"\n" +
	"\fcontribution\x18\x06 \x01(\x01R\fcontribution\x12\x1a\n" +
	"\bevidence\x18\a \x03(\tR\bevidence\"\xd1\x03\n" +
	"\x14ArticleProcessResult\x12\x1d\n" +
	"\n" +
	"article_id\x18\x01 \x01(\tR\tarticleId\x12\x12\n" +
	"\x04keep\x18\x02 \x01(\bR\x04keep\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x01R\x05score\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12\x1b\n" +
	"\tpost_text\x18\x05 \x01(\tR\bpostText\x12\x1d\n" +
	"\n" +
	"check_pass\x18\x06 \x01(\bR\tcheckPass\x12\x16\n" +
	"\x06issues\x18\a \x03(\tR\x06issues\x125\n" +
	"\rmcp_call_logs\x18\b \x03(\v2\x11.agent.McpCallLogR\vmcpCallLogs\x12B\n" +
	"\x0fscore_breakdown\x18\t \x03(\v2\x19.agent.ScoreBreakdownItemR\x0escoreBreakdown\x125\n" +
	"\x16recommendation_reasons\x18\n" +
	" \x03(\tR\x15recommendationReasons\x12+\n" +
	"\x11rejection_reasons\x18\v \x03(\tR\x10rejectionReasons\x12#\n" +
	"\rrank_position\x18\f \x01(\x05R\frankPosition\"g\n" +
	"\x17ProcessArticlesResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x125\n" +
	"\aresults\x18\x02 \x03(\v2\x1b.agent.ArticleProcessResultR\aresults\"\xde\x02\n" +
	"\fFeedbackItem\x12\x1f\n" +
	"\vfeedback_id\x18\x01 \x01(\tR\n" +
	"feedbackId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"article_id\x18\x03 \x01(\tR\tarticleId\x12\x17\n" +
	"\apost_id\x18\x04 \x01(\tR\x06postId\x12#\n" +
	"\rfeedback_text\x18\x05 \x01(\tR\ffeedbackText\x12#\n" +
	"\rfeedback_type\x18\x06 \x01(\tR\ffeedbackType\x12\x16\n" +
	"\x06rating\x18\a \x01(\x05R\x06rating\x12=\n" +
	"\bmetadata\x18\b \x03(\v2!.agent.FeedbackItem.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc5\x02\n" +
	"\x16ProcessFeedbackRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12/\n" +
	"\bfeedback\x18\x02 \x03(\v2\x13.agent.FeedbackItemR\bfeedback\x12j\n" +
	"\x15user_profile_snapshot\x18\x03 \x03(\v26.agent.ProcessFeedbackRequest.UserProfileSnapshotEntryR\x13userProfileSnapshot\x12/\n" +
	"\n" +
	"mcp_policy\x18\x04 \x01(\v2\x10.agent.McpPolicyR\tmcpPolicy\x1aF\n" +
	"\x18UserProfileSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xdb\x03\n" +
	"\x17ProcessFeedbackResponse\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\x12\x1c\n" +
	"\tsentiment\x18\x02 \x01(\tR\tsentiment\x12-\n" +
	"\x12extracted_feedback\x18\x03 \x03(\tR\x11extractedFeedback\x12t\n" +
	"\x18updated_profile_snapshot\x18\x04 \x03(\v2:.agent.ProcessFeedbackResponse.UpdatedProfileSnapshotEntryR\x16updatedProfileSnapshot\x125\n" +
	"\rmcp_call_logs\x18\x05 \x03(\v2\x11.agent.McpCallLogR\vmcpCallLogs\x128\n" +
	"\x18structured_feedback_json\x18\x06 \x01(\tR\x16structuredFeedbackJson\x12*\n" +
	"\x11profile_diff_json\x18\a \x01(\tR\x0fprofileDiffJson\x1aI\n" +
	"\x1bUpdatedProfileSnapshotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\",\n" +
	"\x12HealthCheckRequest\x12\x16\n" +
	"\x06client\x18\x01 \x01(\tR\x06client\"\x8b\x01\n" +
	"\x13HealthCheckResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12%\n" +
	"\x0eenabled_agents\x18\x03 \x03(\tR\renabledAgents\x12\x1b\n" +
	"\tmock_mode\x18\x04 \x01(\bR\bmockMode2\xf8\x01\n" +
	"\fAgentService\x12D\n" +
	"\vHealthCheck\x12\x19.agent.HealthCheckRequest\x1a\x1a.agent.HealthCheckResponse\x12P\n" +
	"\x0fProcessArticles\x12\x1d.agent.ProcessArticlesRequest\x1a\x1e.agent.ProcessArticlesResponse\x12P\n" +
	"\x0fProcessFeedback\x12\x1d.agent.ProcessFeedbackRequest\x1a\x1e.agent.ProcessFeedbackResponseB$Z\"knowledge-post-agent/proto/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_agent_proto_goTypes = []any{
	(*Article)(nil),                 // 0: agent.Article
	(*McpPolicy)(nil),               // 1: agent.McpPolicy
	(*McpCallLog)(nil),              // 2: agent.McpCallLog
	(*ProcessArticlesRequest)(nil),  // 3: agent.ProcessArticlesRequest
	(*ScoreBreakdownItem)(nil),      // 4: agent.ScoreBreakdownItem
	(*ArticleProcessResult)(nil),    // 5: agent.ArticleProcessResult
	(*ProcessArticlesResponse)(nil), // 6: agent.ProcessArticlesResponse
	(*FeedbackItem)(nil),            // 7: agent.FeedbackItem
	(*ProcessFeedbackRequest)(nil),  // 8: agent.ProcessFeedbackRequest
	(*ProcessFeedbackResponse)(nil), // 9: agent.ProcessFeedbackResponse
	(*HealthCheckRequest)(nil),      // 10: agent.HealthCheckRequest
	(*HealthCheckResponse)(nil),     // 11: agent.HealthCheckResponse
	nil,                             // 12: agent.ProcessArticlesRequest.UserProfileSnapshotEntry
	nil,                             // 13: agent.FeedbackItem.MetadataEntry
	nil,                             // 14: agent.ProcessFeedbackRequest.UserProfileSnapshotEntry
	nil,                             // 15: agent.ProcessFeedbackResponse.UpdatedProfileSnapshotEntry
}
var file_agent_proto_depIdxs = []int32{
	0,  // 0: agent.ProcessArticlesRequest.articles:type_name -> agent.Article
	12, // 1: agent.ProcessArticlesRequest.user_profile_snapshot:type_name -> agent.ProcessArticlesRequest.UserProfileSnapshotEntry
	1,  // 2: agent.ProcessArticlesRequest.mcp_policy:type_name -> agent.McpPolicy
	2,  // 3: agent.ArticleProcessResult.mcp_call_logs:type_name -> agent.McpCallLog
	4,  // 4: agent.ArticleProcessResult.score_breakdown:type_name -> agent.ScoreBreakdownItem
	5,  // 5: agent.ProcessArticlesResponse.results:type_name -> agent.ArticleProcessResult
	13, // 6: agent.FeedbackItem.metadata:type_name -> agent.FeedbackItem.MetadataEntry
	7,  // 7: agent.ProcessFeedbackRequest.feedback:type_name -> agent.FeedbackItem
	14, // 8: agent.ProcessFeedbackRequest.user_profile_snapshot:type_name -> agent.ProcessFeedbackRequest.UserProfileSnapshotEntry
	1,  // 9: agent.ProcessFeedbackRequest.mcp_policy:type_name -> agent.McpPolicy
	15, // 10: agent.ProcessFeedbackResponse.updated_profile_snapshot:type_name -> agent.ProcessFeedbackResponse.UpdatedProfileSnapshotEntry
	2,  // 11: agent.ProcessFeedbackResponse.mcp_call_logs:type_name -> agent.McpCallLog
	10, // 12: agent.AgentService.HealthCheck:input_type -> agent.HealthCheckRequest
	3,  // 13: agent.AgentService.ProcessArticles:input_type -> agent.ProcessArticlesRequest
	8,  // 14: agent.AgentService.ProcessFeedback:input_type -> agent.ProcessFeedbackRequest
	11, // 15: agent.AgentService.HealthCheck:output_type -> agent.HealthCheckResponse
	6,  // 16: agent.AgentService.ProcessArticles:output_type -> agent.ProcessArticlesResponse
	9,  // 17: agent.AgentService.ProcessFeedback:output_type -> agent.ProcessFeedbackResponse
	15, // [15:18] is the sub-list for method output_type
	12, // [12:15] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
