CREATE TABLE IF NOT EXISTS articles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  article_uid VARCHAR(128) NOT NULL,
  source VARCHAR(128) NOT NULL DEFAULT '',
  source_type VARCHAR(64) NOT NULL DEFAULT '',
  url VARCHAR(1024) NOT NULL DEFAULT '',
  normalized_url VARCHAR(2048) NULL,
  url_hash CHAR(64) NULL,
  title VARCHAR(512) NOT NULL,
  normalized_title VARCHAR(512) NOT NULL DEFAULT '',
  title_hash CHAR(64) NULL,
  content MEDIUMTEXT NULL,
  raw_content MEDIUMTEXT NULL,
  clean_content MEDIUMTEXT NULL,
  content_hash CHAR(64) NULL,
  language VARCHAR(16) NOT NULL DEFAULT 'unknown',
  author VARCHAR(255) NOT NULL DEFAULT '',
  published_at DATETIME NULL,
  tags JSON NULL,
  fetch_status VARCHAR(32) NOT NULL DEFAULT 'success',
  fetch_error_type VARCHAR(64) NOT NULL DEFAULT '',
  fetch_error TEXT NULL,
  http_status INT NULL,
  raw_payload JSON NULL,
  raw_json JSON NULL,
  fetched_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_articles_article_uid (article_uid),
  UNIQUE KEY uk_articles_url_hash (url_hash),
  UNIQUE KEY uk_articles_title_hash (title_hash),
  UNIQUE KEY uk_articles_content_hash (content_hash),
  KEY idx_articles_source_created (source, created_at),
  KEY idx_articles_normalized_url (normalized_url(768)),
  KEY idx_articles_source_type_published (source_type, published_at),
  KEY idx_articles_language_created (language, created_at),
  KEY idx_articles_fetch_status_created (fetch_status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS crawl_source_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(128) NOT NULL,
  source_name VARCHAR(128) NOT NULL,
  source_type VARCHAR(64) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL,
  error_type VARCHAR(64) NOT NULL DEFAULT '',
  error_message TEXT NULL,
  http_status INT NULL,
  items_found INT NOT NULL DEFAULT 0,
  items_saved INT NOT NULL DEFAULT 0,
  items_partial INT NOT NULL DEFAULT 0,
  items_failed INT NOT NULL DEFAULT 0,
  started_at DATETIME NOT NULL,
  finished_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_crawl_source_run (run_id, source_name),
  KEY idx_crawl_source_status_created (status, created_at),
  KEY idx_crawl_source_name_created (source_name, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  post_uid VARCHAR(128) NOT NULL,
  article_uid VARCHAR(128) NOT NULL DEFAULT '',
  title VARCHAR(512) NOT NULL,
  markdown MEDIUMTEXT NOT NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'draft',
  tags JSON NULL,
  metadata JSON NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_posts_post_uid (post_uid),
  KEY idx_posts_article_uid (article_uid),
  KEY idx_posts_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS feedback_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(128) NOT NULL,
  post_uid VARCHAR(128) NOT NULL DEFAULT '',
  article_uid VARCHAR(128) NOT NULL DEFAULT '',
  user_id VARCHAR(128) NOT NULL DEFAULT '',
  feedback_type VARCHAR(64) NOT NULL DEFAULT '',
  rating INT NULL,
  comment TEXT NULL,
  metadata JSON NULL,
  idempotency_key VARCHAR(128) NOT NULL DEFAULT '',
  raw_feedback_json JSON NULL,
  structured_feedback_json JSON NULL,
  process_status VARCHAR(32) NOT NULL DEFAULT 'received',
  profile_version INT NULL,
  error_message TEXT NULL,
  processed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_feedback_run_id (run_id),
  UNIQUE KEY uk_feedback_idempotency (user_id, idempotency_key),
  KEY idx_feedback_user_created (user_id, created_at),
  KEY idx_feedback_status_created (process_status, created_at),
  KEY idx_feedback_user_profile_version (user_id, profile_version)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS run_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(128) NOT NULL,
  status VARCHAR(64) NOT NULL,
  input_count INT NOT NULL DEFAULT 0,
  output_count INT NOT NULL DEFAULT 0,
  error_message TEXT NULL,
  metadata JSON NULL,
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_run_logs_run_id (run_id),
  KEY idx_run_logs_status_created (status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS task_runs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(128) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  user_id VARCHAR(128) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  current_step VARCHAR(128) NOT NULL DEFAULT '',
  idempotency_key VARCHAR(128) NOT NULL DEFAULT '',
  input_summary TEXT NULL,
  output_summary TEXT NULL,
  error_message TEXT NULL,
  input_payload_json JSON NULL,
  partial_result_json JSON NULL,
  retry_count INT NOT NULL DEFAULT 0,
  max_retries INT NOT NULL DEFAULT 3,
  timeout_seconds INT NOT NULL DEFAULT 120,
  cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
  locked_by VARCHAR(128) NOT NULL DEFAULT '',
  started_at DATETIME NULL,
  finished_at DATETIME NULL,
  next_retry_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_task_runs_run_id (run_id),
  KEY idx_task_runs_idempotency (task_type, user_id, idempotency_key),
  KEY idx_task_runs_status_created (status, created_at),
  KEY idx_task_runs_user_status (user_id, status),
  KEY idx_task_runs_type_status (task_type, status),
  KEY idx_task_runs_retry (status, next_retry_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- task_runs.status values: pending, running, completed, failed, partially_completed, cancelled.

CREATE TABLE IF NOT EXISTS task_steps (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  run_id VARCHAR(128) NOT NULL,
  step_name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  input_summary TEXT NULL,
  output_summary TEXT NULL,
  error_message TEXT NULL,
  retry_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_task_steps_run_step (run_id, step_name),
  KEY idx_task_steps_run_status (run_id, status),
  KEY idx_task_steps_status_updated (status, updated_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS user_profile_snapshot (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  user_id VARCHAR(128) NOT NULL,
  summary TEXT NULL,
  snapshot_json JSON NOT NULL,
  version INT NOT NULL DEFAULT 1,
  base_version INT NULL,
  run_id VARCHAR(128) NOT NULL DEFAULT '',
  diff_json JSON NULL,
  change_reason VARCHAR(128) NOT NULL DEFAULT '',
  source_feedback_id BIGINT UNSIGNED NULL,
  is_active BOOLEAN NOT NULL DEFAULT FALSE,
  rolled_back_from_version INT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_profile_user_version (user_id, version),
  KEY idx_user_profile_user_created (user_id, created_at),
  KEY idx_profile_user_active (user_id, is_active),
  KEY idx_profile_run_id (run_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS memory_compensation_tasks (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  task_id VARCHAR(128) NOT NULL,
  run_id VARCHAR(128) NOT NULL,
  user_id VARCHAR(128) NOT NULL,
  task_type VARCHAR(64) NOT NULL,
  target_system VARCHAR(32) NOT NULL,
  payload_json JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'pending',
  attempt_count INT NOT NULL DEFAULT 0,
  max_attempts INT NOT NULL DEFAULT 5,
  next_retry_at DATETIME NULL,
  last_error TEXT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uk_memory_compensation_task_id (task_id),
  KEY idx_memory_compensation_status_retry (status, next_retry_at),
  KEY idx_memory_compensation_run (run_id),
  KEY idx_memory_compensation_user (user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS mcp_call_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  call_id VARCHAR(64) NOT NULL,
  run_id VARCHAR(128) NOT NULL,
  agent_name VARCHAR(128) NOT NULL DEFAULT '',
  server_name VARCHAR(128) NOT NULL,
  tool_name VARCHAR(128) NOT NULL,
  request_json JSON NULL,
  response_json JSON NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'success',
  error_message TEXT NULL,
  success BOOLEAN NOT NULL DEFAULT TRUE,
  latency_ms BIGINT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_mcp_call_id (call_id),
  KEY idx_mcp_call_run_id (run_id),
  KEY idx_mcp_call_agent_tool (agent_name, tool_name),
  KEY idx_mcp_call_status (status),
  KEY idx_mcp_call_server_tool (server_name, tool_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
